### ISSUE TITLE
Idea to improve UX on Project 5: Recreating a form

### ISSUE THREAD

**Issue by bpires** [ManoloEstevez/RocketSeat-Explorer#1]
Hey Manolo, your form turned out really great, congratulations my friend!

I just wanted to share with you a little idea for improving the user's experience regarding the date and time inputs.

See, on the date label you already specified the date input format "DD/MM/AAAA". In this manner, the date input having a placeholder can be seen as a bit redundant. As no input in the form has placeholders, you could also suppress the time input placeholders as well, it'll make the form design more cohesive.

Thus, in date and time inputs, the browser placeholder will pop up by default. But you can suppress it by turning the input into a text type and using an [`onfocus`](https://www.w3schools.com/jsref/event_onfocus.asp) event with a [`this`](https://www.w3schools.com/js/js_this.asp) keyword to turn the input into a date or time type when the user clicks on the field. You can also use [`mouseover`](https://www.w3schools.com/jsref/event_onmouseover.asp) event (try both and see what suits you better).

```HTML
      <fieldset>
        <div class="fieldset-wrapper">
          <legend>Seus horários disponíveis</legend>
          <legend class="legend-date">Primeira Mentoria</legend>
          <div class="col-3">
            <div class="input-wrapper">
              <label for="mentoring-first-date">Data<span>(DD/MM/AAAA)</span></label>
              <input type="text" onfocus="(this.type = 'date')" id="mentoring-first-date" required />
            </div>
            <div class="input-wrapper">
              <label for="mentoring-first-of">Das</label>
              <input type="text" onfocus="(this.type = 'time')" id="mentoring-first-of" required />
            </div>
            <div class="input-wrapper">
              <label for="mentoring-mentoring-first-util">Até</label>
              <input type="text" onfocus="(this.type = 'time')" id="mentoring-mentoring-first-util" required />
            </div>
          </div>
        </div>
```

This would be the result (modified inputs on top, original on bottom):

![result](https://user-images.githubusercontent.com/86871991/165757585-0e549f4f-0056-4c78-bf00-5a56a579f43b.png)

It's just a suggestion for a minor detail, but it's my way to contribute! 

🚀 Keep going!

**Comment by ManoloEstevez** [comment]
Hello my friend!

Thank you so much for your tips! They may seem to be small details, but they certainly make all the difference to the interaction with the final user!
Besides, another look at your code from someone else is always good!

Let's always contribute with the community. 🚀
